from typing import Literal

USER_AGENT = "Linguee API proxy (https://github.com/imankulov/linguee-api)"
LanguageCode = Literal[
    "BG",
    "CS",
    "DA",
    "DE",
    "EL",
    "EN",
    "ES",
    "ET",
    "FI",
    "FR",
    "HU",
    "IT",
    "JA",
    "LT",
    "LV",
    "MT",
    "NL",
    "PL",
    "PT",
    "RO",
    "RU",
    "SK",
    "SL",
    "SV",
    "ZH",
]
LANGUAGES = {
    "BG": "bulgarian",
    "CS": "czech",
    "DA": "danish",
    "DE": "german",
    "EL": "greek",
    "EN": "english",
    "ES": "spanish",
    "ET": "estonian",
    "FI": "finnish",
    "FR": "french",
    "HU": "hungarian",
    "IT": "italian",
    "JA": "japanese",
    "LT": "lithuanian",
    "LV": "latvian",
    "MT": "maltese",
    "NL": "dutch",
    "PL": "polish",
    "PT": "portuguese",
    "RO": "romanian",
    "RU": "russian",
    "SK": "slovak",
    "SL": "slovene",
    "SV": "swedish",
    "ZH": "chinese",
}
MAX_REDIRECTS = 5
